server:
  port: 8081

spring:
  application:
    name: user-service

  security:
    user:
      name: user
      password: root

  datasource:
    url: jdbc:postgresql://localhost:5432/${DB_NAME:ecommerce_user_db}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true


jwt:
  secret: ${JWT_SECRET}
  access-token-expiry: 900000
  refresh-token-expiry: 604800000